### ISSUE TITLE
好奇后段回环融合部分代码的实现

### ISSUE THREAD

**Issue by xuwuzhou** [kinggreat24/dv-loam#2]
您好，根据您的论文，后段回环融合是对于每一对输入帧，提取出视觉ORB特征和激光Iris特征，然后根据这两个方法并行的提取匹配对, 一旦成功提取一个候选者，就执行几何一致性验证，然后通过Teasr获取匹配对的位姿，并且通过V-GICP优化, 比较好奇这部分代码的具体实现。
大概还需要多长时间整理出代码呢。
这部分代码的确有效的话，会在未来的工作中引用您的这篇论文。

**Comment by kinggreat24** [comment]
不好意思，刚看到，这个闭环检测的策略是有效的,我以前直接尝试使用icp 的方式来做，发现虽然可以成功检测到闭环，但是相对变换的计算有时候却不收敛，有时候即使是收敛的，但是收敛到了错误的位置。所以teaser是很有必要的，至于这部分的代码我现在的工作还要用到，等弄完了我会上传的。你可以参考mulls- slam，isc- slam以及orb- slam的闭环部分，我的代码也基本是从这几个里面整合的。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xuwuzhou ***@***.***&gt;
发送时间: 2021年10月13日 14:36
收件人: kinggreat24/dv-loam ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[kinggreat24/dv-loam] 好奇后段回环融合部分代码的实现 (#2)





 
您好，根据您的论文，后段回环融合是对于每一对输入帧，提取出视觉ORB特征和激光Iris特征，然后根据这两个方法并行的提取匹配对, 一旦成功提取一个候选者，就执行几何一致性验证，然后通过Teasr获取匹配对的位姿，并且通过V-GICP优化, 比较好奇这部分代码的具体实现。
 大概还需要多长时间整理出代码呢。
 这部分代码的确有效的话，会在未来的工作中引用您的这篇论文。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xuwuzhou** [comment]
好的，谢谢，闭环主要是卡在代码的融合方面。感觉代码融合起来有点复杂，hhh
